on:
  push:
  schedule:
    - # ~6am AEST
    - cron: "19 19 * * *"
permissions:
  contents: write # let the action push the commit it made
jobs:
  bump_versions:
    name: Bump Dependency Versions
    runs-on:
      ubuntu-22.04
    steps:
      - name: git checkout
        uses: actions/checkout@v4
      - name: Install Nix via Cachix
        if: env.using_self_hosted_runner_with_nix != 'true'
        uses: cachix/install-nix-action@v25
        with:
          install_url: "https://releases.nixos.org/nix/nix-2.18.1/install"
      - name: Run the Magic Nix Cache # https://determinate.systems/posts/magic-nix-cache
        uses: DeterminateSystems/magic-nix-cache-action@v2
      - name: pull dev environment
        run: |
          nix develop --command \
            echo dev environment ready
      - name: prep git
        run: |
          set -e
          git fetch
          git checkout main
          git config --global user.name 'BumpBot'
          git config --global user.email 'robert.k.bell+bumpbot@gmail.com'
      - name: update deps
        run: |
          nix develop --command \
            ./bin/update
      - name: commit changes
        run: |
          nix develop --command \
            ./bin/commit
      - name: push to origin
        run: git push
